spring.application.name=onemoretime
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# This line is magic: It tells Hibernate to automatically create the tables for you!
spring.jpa.hibernate.ddl-auto=update